import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BodyBG from "@/assets/p.svg";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MH1014",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ background: `url(${BodyBG.src})` }}
      >
        <main className="max-w-3xl mx-auto">
          <header>
            <Navbar />
          </header>
          {children}
          <footer></footer>
        </main>
      </body>
    </html>
  );
}
